{% set name = "dwave-cloud-client" %}
{% set version = "0.13.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 25a681acdf969e92913f2c90a3f11dccd5729161ba7327f79779ee4f3668ce9d

build:
  entry_points:
    - dwave = dwave.cloud.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=46.4.0
    - wheel
  run:
    - typing_extensions >=4.5.0,<5
    - orjson >=3.10
    - urllib3 >=1.26,<3
    - importlib-metadata >=5.0.0
    - authlib >=1.2,<2
    - typing-extensions >=4.5.0,<5
    - packaging >=19
    - werkzeug >=2.2,<4
    - click >=7.0,<9
    - diskcache >=5.2.1,<6
    - homebase >=1.0,<2
    - plucky >=0.4.3,<0.5
    - pydantic >=2,<3
    - python >={{ python_min }}
    - python-dateutil >=2.7,<3
    - requests >=2.25,<3
    # From requests[socks]
    - PySocks >=1.5.6,!=1.5.7

test:
  imports:
    - dwave
  commands:
    - pip check
    - dwave --help
  requires:
    - pip
    - numpy
    - python {{ python_min }}

about:
  home: https://github.com/dwavesystems/dwave-cloud-client
  summary: A minimal client for interacting with D-Wave cloud resources.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
