{% set name = "dwave-cloud-client" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-cloud-client-{{ version }}.tar.gz
  sha256: 92e7911e6ad8e676cb3898ed2522c22269de31c551d75677b5c875a3ed1ac933

build:
  entry_points:
    - dwave = dwave.cloud.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=7.0
    - dataclasses
    - diskcache >=5.2.1
    - homebase >=1.0
    - plucky >=0.4.3
    - pydantic >=1.7.3
    - python >=3.6
    - python-dateutil >=2.7
    - requests >=2.18
    # From requests[socks]
    - PySocks >=1.5.6,!=1.5.7
  run_constrained:
    - dimod >=0.10.5,<0.11,!=0.10.0,!=0.10.1,!=0.10.2,!=0.10.3,!=0.10.4
    - numpy >=1.16
    - dwave-networkx >=0.8.9

test:
  imports:
    - dwave
  commands:
    - pip check
    - dwave --help
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dwave-cloud-client
  summary: A minimal client for interacting with D-Wave cloud resources.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
