{% set name = "dwave-cloud-client" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-cloud-client-{{ version }}.tar.gz
  sha256: f1541ceae1100ad80214b583a5c5c0323ec24b7bc31c7917fe8f57e287cc1776

build:
  entry_points:
    - dwave = dwave.cloud.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - orjson >=3.10
    - urllib3 >=1.26,<3
    - importlib-metadata >=5.0.0
    - authlib >=1.2,<2
    - typing-extensions >=4.5.0,<5
    - packaging >=19
    - werkzeug >=2.2,<4
    - click >=7.0,<9
    - dataclasses
    - diskcache >=5.2.1,<6
    - homebase >=1.0,<2
    - plucky >=0.4.3,<0.5
    - pydantic >=2,<3
    - python >=3.8
    - python-dateutil >=2.7,<3
    - requests >=2.25,<3
    # From requests[socks]
    - PySocks >=1.5.6,!=1.5.7
  run_constrained:
    - dimod >=0.10.5,<0.13,!=0.11.4
    - numpy >=1.17.3
    - dwave-networkx >=0.8.9

test:
  imports:
    - dwave
  commands:
    - pip check
    - dwave --help
  requires:
    - pip
    - numpy

about:
  home: https://github.com/dwavesystems/dwave-cloud-client
  summary: A minimal client for interacting with D-Wave cloud resources.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
