{% set name = "dwave-cloud-client" %}
{% set version = "0.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dwave-cloud-client-{{ version }}.tar.gz
  sha256: cde93a4e70da6fe4147ffcb29b1cd05302ed374901c98f0fdcff5ab8a94d4229

build:
  entry_points:
    - dwave = dwave.cloud.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - packaging >=19
    - werkzeug >=2.2
    - click >=7.0
    - dataclasses
    - diskcache >=5.2.1
    - homebase >=1.0
    - plucky >=0.4.3
    - pydantic >=1.7.3
    - python >=3.7
    - python-dateutil >=2.7
    - requests >=2.18
    # From requests[socks]
    - PySocks >=1.5.6,!=1.5.7
  run_constrained:
    - dimod >=0.10.5,<0.13,!=0.11.4
    - numpy >=1.17.3
    - dwave-networkx >=0.8.9

test:
  imports:
    - dwave
  commands:
    - pip check
    - dwave --help
  requires:
    - pip
    - numpy

about:
  home: https://github.com/dwavesystems/dwave-cloud-client
  summary: A minimal client for interacting with D-Wave cloud resources.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
